window.GP_WORDS_MD_LISTS = {
  "de_commands": [
    "erkläre",
    "erkläre schritt für schritt",
    "fasse zusammen",
    "beschreibe",
    "analysiere",
    "vergleiche",
    "diskutiere",
    "zeige",
    "definiere",
    "liste auf",
    "erstelle",
    "entwickle",
    "argumentiere",
    "interpretiere",
    "begründe",
    "wähle",
    "bewerte",
    "kritisiere",
    "beurteile",
    "skizziere",
    "demonstriere",
    "formuliere",
    "ordne",
    "plane",
    "entwickle eine strategie",
    "prüfe",
    "untersuche",
    "erläutere",
    "begründe deine wahl",
    "entscheide",
    "kalkuliere",
    "rechne vor",
    "leite ab",
    "identifiziere",
    "veranschauliche",
    "erkläre den unterschied",
    "beschreibe die funktion",
    "führe aus",
    "liste die schritte auf",
    "schlage vor",
    "entwickle   ein beispiel",
    "zeige eine lösung",
    "leite eine methode ab",
    "erstelle eine tabelle",
    "fertige ein diagramm an",
    "formuliere ein szenario",
    "argumentiere für",
    "argumentiere gegen",
    "fasse die kernaussagen zusammen",
    "notiere",
    "erkenne muster",
    "interpretiere ergebnisse",
    "erkläre ursache und wirkung",
    "untersuche die zusammenhänge",
    "beschreibe die folgen",
    "entwickle eine hypothese",
    "formuliere eine fragestellung",
    "belege",
    "ordne nach priorität",
    "erstelle eine liste",
    "skizziere ein modell",
    "leite regeln ab",
    "erläutere unterschiede",
    "fasse die argumente zusammen",
    "formuliere empfehlungen",
    "wähle die beste option",
    "prüfe die gültigkeit",
    "bewerten",
    "analysiere kritisch",
    "entwickle eine lösung",
    "überprüfe",
    "erkläre den prozess",
    "simuliere",
    "demonstriere die anwendung",
    "zeige beispiele",
    "identifiziere probleme",
    "beschreibe lösungsansätze",
    "erkläre die methodik",
    "leite maßnahmen ab",
    "formuliere zielsetzungen",
    "ordne kategorien",
    "untersuche ursachen",
    "vergleiche alternativen",
    "illustriere",
    "entwickle strategien",
    "fasse zusammen in einem satz",
    "erläutere den zusammenhang",
    "argumentiere logisch",
    "zeige unterschiede auf",
    "beschreibe eigenschaften",
    "beurteile die relevanz",
    "identifiziere trends",
    "erkläre vorteile und nachteile",
    "analysiere daten",
    "leite schlussfolgerungen ab",
    "formuliere handlungsempfehlungen",
    "priorisiere",
    "vergleiche szenarien",
    "dokumentiere",
    "evaluiere",
    "erkläre unterschiede",
    "entwickle lösungen",
    "plane aktivitäten",
    "beschreibe prozesse",
    "analysiere ursachen",
    "ermittele risiken",
    "erkläre beispiele",
    "ordne prioritäten",
    "erläutere optionen",
    "formuliere anweisungen",
    "fasse die ergebnisse zusammen",
    "beschreibe unterschiede",
    "veranschauliche ergebnisse",
    "leite erkenntnisse ab",
    "analysiere ergebnisse",
    "leite hypothesen ab",
    "erkläre logik",
    "bewerte optionen",
    "entwickle konzepte",
    "erkläre die schritte",
    "prüfe gültigkeit",
    "zeige zusammenhänge auf",
    "untersuche trends",
    "formuliere richtlinien",
    "vergleiche kriterien",
    "identifiziere muster",
    "erläutere vorgehensweisen",
    "beschreibe abläufe",
    "entwickle empfehlungen",
    "skizziere prozesse",
    "visualisiere daten",
    "formuliere ziele",
    "berechne",
    "führe berechnungen durch",
    "erkläre zusammenhänge",
    "illustriere unterschiede",
    "fasse beobachtungen zusammen",
    "interpretiere daten",
    "argumentiere strukturiert",
    "entwickle szenarien",
    "prüfe hypothesen",
    "formuliere strategien",
    "analysiere optionen",
    "identifiziere lösungen",
    "beschreibe mechanismen",
    "ordne prozesse",
    "erkläre methoden",
    "leite prozesse ab",
    "entwickle vorgehensmodelle",
    "erläutere funktionalitäten",
    "zeige unterschiede",
    "beschreibe ergebnisse",
    "skizziere modelle",
    "analysiere zusammenhänge",
    "leite konsequenzen ab",
    "definiere begriffe",
    "entwickle anwendungsfälle",
    "vergleiche methoden",
    "erkläre abläufe",
    "beurteile strategien",
    "illustriere konzepte",
    "leite muster ab",
    "fasse informationen zusammen",
    "visualisiere prozesse",
    "zeige ursachen",
    "analysiere probleme",
    "ordne szenarien",
    "skizziere handlungsoptionen",
    "erläutere vorgehensweise",
    "formuliere maßnahmen",
    "ich möchte"
  ],
  "en_commands": [
    "explain",
    "explain step by step",
    "summarize",
    "describe",
    "analyze",
    "compare",
    "discuss",
    "show",
    "define",
    "list",
    "create",
    "develop",
    "argue",
    "interpret",
    "justify",
    "choose",
    "evaluate",
    "critique",
    "assess",
    "outline",
    "plan",
    "develop a strategy",
    "check",
    "examine",
    "elaborate",
    "provide reasoning",
    "decide",
    "calculate",
    "illustrate",
    "derive",
    "identify",
    "demonstrate the difference",
    "describe the function",
    "execute",
    "list the steps",
    "propose",
    "develop an example",
    "show a solution",
    "derive a method",
    "create a table",
    "draw a diagram",
    "formulate a scenario",
    "argue for",
    "argue against",
    "summarize the key points",
    "note",
    "recognize patterns",
    "interpret results",
    "explain cause and effect",
    "examine relationships",
    "describe consequences",
    "develop a hypothesis",
    "formulate a research question",
    "support with evidence",
    "prioritize",
    "create a list",
    "sketch a model",
    "derive rules",
    "explain differences",
    "summarize arguments",
    "formulate recommendations",
    "select the best option",
    "validate",
    "analyze critically",
    "develop a solution",
    "verify",
    "explain the process",
    "simulate",
    "demonstrate application",
    "provide examples",
    "identify problems",
    "describe solutions",
    "explain methodology",
    "derive measures",
    "formulate objectives",
    "categorize",
    "investigate causes",
    "compare alternatives",
    "develop strategies",
    "summarize in one sentence",
    "explain relationships",
    "argue logically",
    "highlight differences",
    "describe properties",
    "assess relevance",
    "identify trends",
    "explain advantages and disadvantages",
    "analyze data",
    "draw conclusions",
    "formulate action recommendations",
    "compare scenarios",
    "document",
    "explain distinctions",
    "develop solutions",
    "plan activities",
    "describe processes",
    "analyze causes",
    "determine risks",
    "explain examples",
    "outline priorities",
    "explain options",
    "formulate instructions",
    "summarize results",
    "describe differences",
    "visualize results",
    "derive insights",
    "analyze outcomes",
    "derive hypotheses",
    "explain logic",
    "assess options",
    "develop concepts",
    "explain steps",
    "verify validity",
    "show connections",
    "examine trends",
    "formulate guidelines",
    "compare criteria",
    "identify patterns",
    "explain procedures",
    "describe workflows",
    "develop recommendations",
    "sketch processes",
    "visualize data",
    "formulate goals",
    "perform calculations",
    "illustrate differences",
    "summarize observations",
    "interpret data",
    "argue in a structured way",
    "develop scenarios",
    "test hypotheses",
    "formulate strategies",
    "analyze options",
    "identify solutions",
    "describe mechanisms",
    "organize processes",
    "explain methods",
    "derive processes",
    "develop process models",
    "explain functionalities",
    "show differences",
    "describe results",
    "sketch models",
    "analyze relationships",
    "derive consequences",
    "define terms",
    "develop use cases",
    "compare methods",
    "explain workflows",
    "assess strategies",
    "illustrate concepts",
    "derive patterns",
    "summarize information",
    "visualize processes",
    "show causes",
    "analyze problems",
    "organize scenarios",
    "sketch action options",
    "formulate measures"
  ],
  "de_polite_smalltalk": [
    "bitte",
    "danke",
    "vielen dank",
    "danke schön",
    "danke sehr",
    "herzlichen dank",
    "vielen herzlichen dank",
    "danke im voraus",
    "besten dank",
    "hallo",
    "hi",
    "hey",
    "guten tag",
    "guten morgen",
    "guten abend",
    "wie geht es dir?",
    "wie geht’s?",
    "alles klar?",
    "ich hoffe",
    "es geht dir gut",
    "alles ist in ordnung",
    "es läuft gut",
    "entschuldige",
    "entschuldigung",
    "tut mir leid",
    "kein problem",
    "keine ursache",
    "gern geschehen",
    "gerne",
    "freut mich",
    "dass ich helfen konnte",
    "schön",
    "dich zu sehen",
    "hallo zusammen",
    "sie haben einen schönen tag",
    "danke für deine antwort",
    "danke für ihre antwort",
    "danke für die rückmeldung",
    "vielen dank für die rückmeldung",
    "bitte sehr",
    "sei so nett und",
    "könnten sie bitte",
    "würdest du bitte",
    "entschuldigen sie",
    "entschuldigen sie bitte",
    "danke für ihre unterstützung",
    "danke für deine unterstützung",
    "das hilft",
    "dass wir sprechen",
    "alles läuft gut bei dir",
    "sie hatten einen guten tag",
    "liebe grüße",
    "viele grüße",
    "mit freundlichen grüßen",
    "alles gute",
    "alles liebe",
    "herzlichen glückwunsch",
    "glückwunsch",
    "viel erfolg",
    "mach’s gut",
    "bis bald",
    "bis später",
    "bis morgen",
    "dass wir uns sprechen",
    "freut mich sehr",
    "super",
    "toll",
    "klasse",
    "prima",
    "großartig",
    "fantastisch",
    "wunderbar",
    "hervorragend",
    "spitze",
    "top",
    "genial",
    "super schön",
    "top klasse",
    "danke für die info",
    "vielen dank für die info",
    "das war hilfreich",
    "es freut mich",
    "dich kennenzulernen",
    "dass wir uns treffen",
    "dass du da bist",
    "schöne grüße",
    "liebevoll",
    "mit herzlichen grüßen",
    "herzlichst",
    "viel spaß",
    "alles beste",
    "danke für ihre hilfe",
    "danke für deine hilfe",
    "das funktioniert",
    "hoffe das passt",
    "alles klar bei dir?",
    "danke nochmal",
    "danke dir",
    "danke vielmals",
    "super gut",
    "klasse gemacht",
    "prima arbeit",
    "danke für die schnelle antwort",
    "danke für die mühe",
    "danke für die zeit",
    "freue mich darauf",
    "hoffe auf deine rückmeldung",
    "danke für die info im voraus"
  ],
  "en_polite_smalltalk": [
    "please",
    "thank you",
    "thanks",
    "thanks a lot",
    "thank you very much",
    "many thanks",
    "thanks in advance",
    "best regards",
    "kind regards",
    "all the best",
    "have a nice day",
    "hope you have a nice day",
    "hello",
    "hi",
    "hey",
    "good morning",
    "good afternoon",
    "good evening",
    "how are you?",
    "how’s it going?",
    "hope you’re doing well",
    "i hope everything is fine",
    "sorry",
    "excuse me",
    "i apologize",
    "my apologies",
    "no problem",
    "you’re welcome",
    "my pleasure",
    "glad to help",
    "nice to see you",
    "pleased to meet you",
    "nice to meet you",
    "welcome",
    "welcome back",
    "congratulations",
    "well done",
    "good luck",
    "take care",
    "see you soon",
    "see you later",
    "see you tomorrow",
    "glad to talk",
    "happy to see you",
    "super",
    "great",
    "excellent",
    "fantastic",
    "wonderful",
    "amazing",
    "top",
    "awesome",
    "brilliant",
    "excellent work",
    "good job",
    "thanks for your reply",
    "thanks for your support",
    "thank you for your support",
    "thanks for your feedback",
    "many thanks for your feedback",
    "i hope this helps",
    "i hope this was helpful",
    "please be so kind",
    "could you please",
    "would you please",
    "excuse me please",
    "thanks for the info",
    "thanks for your help",
    "thanks again",
    "thanks a lot for your time",
    "i hope this works",
    "hope that’s okay",
    "i look forward to your reply",
    "hope everything is okay",
    "nice talking to you",
    "i appreciate it",
    "much appreciated",
    "wonderful to meet you",
    "happy to hear from you"
  ],
  "de_fillers": [
    "also",
    "eigentlich",
    "irgendwie",
    "quasi",
    "eben",
    "halt",
    "mal",
    "ja",
    "nun",
    "dann",
    "doch",
    "vielleicht",
    "vielleicht mal",
    "sozusagen",
    "jedenfalls",
    "genau",
    "tatsächlich",
    "sicherlich",
    "vermutlich",
    "eventuell",
    "naja",
    "letztendlich",
    "schließlich",
    "überhaupt",
    "ehrlich gesagt",
    "genau genommen",
    "im grunde",
    "prinzipiell",
    "selbstverständlich",
    "definitiv",
    "natürlich",
    "übrigens",
    "überhaupt nicht",
    "tja",
    "hmm",
    "ach",
    "oh",
    "aha",
    "hm",
    "ach so",
    "nun ja",
    "im prinzip",
    "im endeffekt",
    "rein theoretisch",
    "gewissermaßen",
    "in etwa",
    "in gewisser weise",
    "letztlich",
    "scheinbar",
    "im wesentlichen",
    "zumindest",
    "möglicherweise",
    "ohne frage",
    "bloß",
    "einfach",
    "kurz gesagt",
    "um ehrlich zu sein",
    "kurzum",
    "ohnehin",
    "jedenfalls mal",
    "so",
    "wie gesagt",
    "im übrigen",
    "im nachhinein",
    "im allgemeinen",
    "im moment",
    "unter anderem",
    "vor allem",
    "rein zufällig",
    "zugegebenermaßen",
    "angenommen",
    "vermutlich mal",
    "wohlgemerkt",
    "zu recht",
    "in der tat",
    "auf jeden fall",
    "immerhin",
    "letztendlich mal",
    "fast",
    "genau so",
    "teilweise",
    "überwiegend",
    "ungefähr",
    "insgesamt",
    "grundsätzlich",
    "demnach",
    "dementsprechend",
    "insgesamt gesehen",
    "im vergleich",
    "im prinzip gesehen",
    "faktisch",
    "praktisch",
    "letztlich gesehen",
    "folglich",
    "zusätzlich",
    "gleichzeitig",
    "parallel",
    "wiederum",
    "andererseits",
    "anderweitig",
    "nebenbei",
    "nebenbei bemerkt",
    "meines erachtens",
    "meiner meinung nach",
    "soweit",
    "soweit ich weiß",
    "soweit bekannt",
    "soweit möglich",
    "soweit vorhanden",
    "soweit relevant",
    "im verhältnis",
    "im sinne",
    "im detail",
    "im großen und ganzen",
    "im ergebnis",
    "in der regel",
    "in der praxis",
    "in wirklichkeit",
    "in etwa genommen",
    "in gewissem maße",
    "in letzter konsequenz",
    "in letzter instanz",
    "in der folge",
    "in bezug auf",
    "im allgemeinen betrachtet",
    "im endeffekt gesehen"
  ],
  "en_fillers": [
    "so",
    "actually",
    "basically",
    "kind of",
    "sort of",
    "like",
    "literally",
    "just",
    "well",
    "anyway",
    "i mean",
    "you know",
    "right",
    "okay",
    "then",
    "now",
    "certainly",
    "probably",
    "maybe",
    "perhaps",
    "obviously",
    "indeed",
    "truly",
    "honestly",
    "quite",
    "really",
    "definitely",
    "naturally",
    "at all",
    "hmm",
    "uh",
    "oh",
    "aha",
    "um",
    "like i said",
    "in fact",
    "generally",
    "essentially",
    "theoretically",
    "roughly",
    "somewhat",
    "finally",
    "apparently",
    "at least",
    "possibly",
    "without a doubt",
    "simply",
    "in short",
    "to be honest",
    "frankly",
    "in essence",
    "in summary",
    "as it were",
    "more or less",
    "to some extent",
    "in a way",
    "in any case",
    "all in all",
    "after all",
    "at the end of the day",
    "as a matter of fact",
    "as far as i know",
    "as i said",
    "as i mentioned",
    "as it happens",
    "by the way",
    "for the most part",
    "in general",
    "in reality",
    "in principle",
    "in the end",
    "on the whole",
    "at any rate",
    "all things considered",
    "so to speak",
    "more specifically",
    "relatively",
    "seemingly",
    "supposedly",
    "overall",
    "fundamentally",
    "primarily",
    "mostly",
    "largely",
    "particularly",
    "roughly speaking",
    "in effect",
    "for instance",
    "incidentally",
    "for example",
    "honestly speaking",
    "frankly speaking",
    "in other words",
    "in brief",
    "at first glance",
    "at first sight",
    "effectively",
    "practically",
    "virtually",
    "nominally",
    "comparatively",
    "moreover",
    "additionally",
    "furthermore",
    "in addition",
    "by and large",
    "in any event",
    "in all likelihood"
  ]
};

